name: think_school
description: "App that teaches you all about business"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  
  paw: ^0.0.4 # logging
  flutter_svg: ^2.0.10+1
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Dm Serif Display
      fonts:
        - asset: fonts/dm_serif_display_regular.ttf
          weight: 400
    - family: Space Grotesk
      fonts:
        - asset: fonts/space_grotesk_light.ttf
          weight: 300
        - asset: fonts/space_grotesk_regular.ttf
          weight: 400
        - asset: fonts/space_grotesk_medium.ttf
          weight: 500
        - asset: fonts/space_grotesk_bold.ttf
          weight: 600
